services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bloggy-app
    depends_on:
      cosmosdb:
        condition: service_healthy
    environment:
      APP_ENVIRONMENT: development
      BLOB_STORAGE_CONNECTION_STRING: ${BLOB_STORAGE_CONNECTION_STRING:?error}
      COSMOS_CONNECTION_STRING: ${COSMOS_CONNECTION_STRING:-AccountEndpoint=https://cosmosdb:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;}
      AUTHENTICATION_JWT_KEY: ${AUTHENTICATION_JWT_KEY:-LocalDevelopmentKey1234_PPlxF1MRYg0/WGWfSzA=}
    ports:
      - 4080:4080
      - 4443:4443
    volumes:
      - .:/src
      # Avoid syncing output
      - /src/bin
      - /src/obj

  client:
    build:
      context: .
      dockerfile: Dockerfile.clientdev
    container_name: bloggy-client
    environment:
      APP_ENVIRONMENT: development
    volumes:
      - ./bloggy-client/src:/app/bloggy-client/src
      - ./bloggy-client/vite.config.ts:/app/bloggy-client/vite.config.ts
      - ./wwwroot:/app/wwwroot
      - /app/bloggy-client/node_modules # Avoid syncing node_modules

  cosmosdb:
    container_name: bloggy-cosmosdb
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 10
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: true
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    tty: true
    restart: unless-stopped
    mem_limit: 2G
    cpu_count: 2
    healthcheck:
      test: curl -f -k https://cosmosdb:8081/_explorer/emulator.pem || exit 1
      start_period: 120s
      interval: 10s
      timeout: 1s
      retries: 5
